/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestionyes (void)
{
  GtkWidget *gestionyes;
  GtkWidget *fixed1;
  GtkWidget *buttongem;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *buttonges;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *buttongech;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *buttongeaff;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *buttongedec;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label7;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeviewgeaff;
  GtkWidget *buttongebest;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label42;
  GtkWidget *buttongea;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *labelge;
  GtkWidget *image21;

  gestionyes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestionyes), _("Gestion de Nutrisionniste"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestionyes), fixed1);

  buttongem = gtk_button_new ();
  gtk_widget_show (buttongem);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongem, 80, 152);
  gtk_widget_set_size_request (buttongem, 112, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttongem), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='red'>Modifier\n</span></b>"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  buttonges = gtk_button_new ();
  gtk_widget_show (buttonges);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonges, 80, 210);
  gtk_widget_set_size_request (buttonges, 112, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonges), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='red'>Supprimer\n</span></b>"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  buttongech = gtk_button_new ();
  gtk_widget_show (buttongech);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongech, 80, 270);
  gtk_widget_set_size_request (buttongech, 112, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttongech), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='red'>Chercher\n</span></b>"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  buttongeaff = gtk_button_new ();
  gtk_widget_show (buttongeaff);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongeaff, 80, 330);
  gtk_widget_set_size_request (buttongeaff, 112, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttongeaff), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-print", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='red'>Afficher\n</span></b>"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  buttongedec = gtk_button_new ();
  gtk_widget_show (buttongedec);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongedec, 80, 390);
  gtk_widget_set_size_request (buttongedec, 112, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttongedec), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='red'>Deconnxion\n</span></b>"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox6), label7, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow1, 208, 88);
  gtk_widget_set_size_request (scrolledwindow1, 552, 328);

  treeviewgeaff = gtk_tree_view_new ();
  gtk_widget_show (treeviewgeaff);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeviewgeaff);
  gtk_widget_set_size_request (treeviewgeaff, 472, 328);

  buttongebest = gtk_button_new ();
  gtk_widget_show (buttongebest);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongebest, 344, 432);
  gtk_widget_set_size_request (buttongebest, 160, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttongebest), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>Meilleur Menu\n</span></b>"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox19), label42, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  buttongea = gtk_button_new ();
  gtk_widget_show (buttongea);
  gtk_fixed_put (GTK_FIXED (fixed1), buttongea, 80, 96);
  gtk_widget_set_size_request (buttongea, 112, 29);
  gtk_button_set_focus_on_click (GTK_BUTTON (buttongea), FALSE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttongea), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='red'>Ajout\n</span></b>"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  labelge = gtk_label_new (_("Gestion De Nutrisionniste"));
  gtk_widget_show (labelge);
  gtk_fixed_put (GTK_FIXED (fixed1), labelge, 272, 32);
  gtk_widget_set_size_request (labelge, 280, 16);

  image21 = create_pixmap (gestionyes, "invi5.png");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed1), image21, 72, 24);
  gtk_widget_set_size_request (image21, 248, 48);

  g_signal_connect ((gpointer) buttongem, "clicked",
                    G_CALLBACK (on_buttongem_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonges, "clicked",
                    G_CALLBACK (on_buttonges_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongech, "clicked",
                    G_CALLBACK (on_buttongech_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongeaff, "clicked",
                    G_CALLBACK (on_buttongeaff_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongedec, "clicked",
                    G_CALLBACK (on_buttongedec_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewgeaff, "row_activated",
                    G_CALLBACK (on_treeviewgeaff_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttongebest, "clicked",
                    G_CALLBACK (on_buttongebest_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongea, "clicked",
                    G_CALLBACK (on_buttongea_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestionyes, gestionyes, "gestionyes");
  GLADE_HOOKUP_OBJECT (gestionyes, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestionyes, buttongem, "buttongem");
  GLADE_HOOKUP_OBJECT (gestionyes, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestionyes, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestionyes, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestionyes, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestionyes, buttonges, "buttonges");
  GLADE_HOOKUP_OBJECT (gestionyes, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestionyes, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestionyes, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestionyes, label4, "label4");
  GLADE_HOOKUP_OBJECT (gestionyes, buttongech, "buttongech");
  GLADE_HOOKUP_OBJECT (gestionyes, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestionyes, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestionyes, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestionyes, label5, "label5");
  GLADE_HOOKUP_OBJECT (gestionyes, buttongeaff, "buttongeaff");
  GLADE_HOOKUP_OBJECT (gestionyes, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestionyes, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestionyes, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestionyes, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestionyes, buttongedec, "buttongedec");
  GLADE_HOOKUP_OBJECT (gestionyes, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestionyes, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestionyes, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestionyes, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestionyes, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestionyes, treeviewgeaff, "treeviewgeaff");
  GLADE_HOOKUP_OBJECT (gestionyes, buttongebest, "buttongebest");
  GLADE_HOOKUP_OBJECT (gestionyes, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (gestionyes, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (gestionyes, image19, "image19");
  GLADE_HOOKUP_OBJECT (gestionyes, label42, "label42");
  GLADE_HOOKUP_OBJECT (gestionyes, buttongea, "buttongea");
  GLADE_HOOKUP_OBJECT (gestionyes, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestionyes, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestionyes, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestionyes, label1, "label1");
  GLADE_HOOKUP_OBJECT (gestionyes, labelge, "labelge");
  GLADE_HOOKUP_OBJECT (gestionyes, image21, "image21");

  return gestionyes;
}

GtkWidget*
create_ajyes (void)
{
  GtkWidget *ajyes;
  GtkWidget *fixed;
  GtkWidget *entrygeaid;
  GtkObject *spinbuttongeanc_adj;
  GtkWidget *spinbuttongeanc;
  GtkWidget *entrygeaqd;
  GtkWidget *calendargea;
  GtkWidget *checkbuttongeaf;
  GtkWidget *checkbuttongeac;
  GtkWidget *checkbuttongeap;
  GtkWidget *radiobuttongeanon;
  GSList *radiobuttongeanon_group = NULL;
  GtkWidget *vseparator1;
  GtkWidget *buttongeaok;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label17;
  GtkWidget *radiobuttongeaoui;
  GtkWidget *labelgeasuc;
  GtkWidget *labelgeaidc;
  GtkWidget *buttongeac;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label18;
  GtkWidget *comboboxentrygeat;
  GtkWidget *image22;
  GtkWidget *labelgeaid;
  GtkWidget *labelgeat;
  GtkWidget *labelgeanc;
  GtkWidget *labelgeaqd;
  GtkWidget *labelgead;
  GtkWidget *labelgeacon;
  GtkWidget *checkbuttongeal;
  GtkWidget *labelgeaeq;
  GtkWidget *labelgea;

  ajyes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajyes), _("Ajout"));

  fixed = gtk_fixed_new ();
  gtk_widget_show (fixed);
  gtk_container_add (GTK_CONTAINER (ajyes), fixed);

  entrygeaid = gtk_entry_new ();
  gtk_widget_show (entrygeaid);
  gtk_fixed_put (GTK_FIXED (fixed), entrygeaid, 208, 112);
  gtk_widget_set_size_request (entrygeaid, 72, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrygeaid), 8226);

  spinbuttongeanc_adj = gtk_adjustment_new (1, 0, 3000, 1, 10, 10);
  spinbuttongeanc = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttongeanc_adj), 1, 0);
  gtk_widget_show (spinbuttongeanc);
  gtk_fixed_put (GTK_FIXED (fixed), spinbuttongeanc, 200, 232);
  gtk_widget_set_size_request (spinbuttongeanc, 60, 27);

  entrygeaqd = gtk_entry_new ();
  gtk_widget_show (entrygeaqd);
  gtk_fixed_put (GTK_FIXED (fixed), entrygeaqd, 200, 272);
  gtk_widget_set_size_request (entrygeaqd, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrygeaqd), 8226);

  calendargea = gtk_calendar_new ();
  gtk_widget_show (calendargea);
  gtk_fixed_put (GTK_FIXED (fixed), calendargea, 208, 336);
  gtk_widget_set_size_request (calendargea, 260, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendargea),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  checkbuttongeaf = gtk_check_button_new_with_mnemonic (_("fruits"));
  gtk_widget_show (checkbuttongeaf);
  gtk_fixed_put (GTK_FIXED (fixed), checkbuttongeaf, 832, 136);
  gtk_widget_set_size_request (checkbuttongeaf, 118, 24);

  checkbuttongeac = gtk_check_button_new_with_mnemonic (_("Cereales"));
  gtk_widget_show (checkbuttongeac);
  gtk_fixed_put (GTK_FIXED (fixed), checkbuttongeac, 832, 176);
  gtk_widget_set_size_request (checkbuttongeac, 118, 24);

  checkbuttongeap = gtk_check_button_new_with_mnemonic (_("Proteines"));
  gtk_widget_show (checkbuttongeap);
  gtk_fixed_put (GTK_FIXED (fixed), checkbuttongeap, 832, 200);
  gtk_widget_set_size_request (checkbuttongeap, 120, 48);

  radiobuttongeanon = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (radiobuttongeanon);
  gtk_fixed_put (GTK_FIXED (fixed), radiobuttongeanon, 832, 304);
  gtk_widget_set_size_request (radiobuttongeanon, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttongeanon), radiobuttongeanon_group);
  radiobuttongeanon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttongeanon));

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed), vseparator1, 640, 72);
  gtk_widget_set_size_request (vseparator1, 16, 512);

  buttongeaok = gtk_button_new ();
  gtk_widget_show (buttongeaok);
  gtk_fixed_put (GTK_FIXED (fixed), buttongeaok, 784, 392);
  gtk_widget_set_size_request (buttongeaok, 72, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttongeaok), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>OK\n</span></b>"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  radiobuttongeaoui = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (radiobuttongeaoui);
  gtk_fixed_put (GTK_FIXED (fixed), radiobuttongeaoui, 832, 264);
  gtk_widget_set_size_request (radiobuttongeaoui, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttongeaoui), radiobuttongeanon_group);
  radiobuttongeanon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttongeaoui));

  labelgeasuc = gtk_label_new ("");
  gtk_widget_show (labelgeasuc);
  gtk_fixed_put (GTK_FIXED (fixed), labelgeasuc, 664, 344);
  gtk_widget_set_size_request (labelgeasuc, 352, 33);

  labelgeaidc = gtk_label_new ("");
  gtk_widget_show (labelgeaidc);
  gtk_fixed_put (GTK_FIXED (fixed), labelgeaidc, 296, 112);
  gtk_widget_set_size_request (labelgeaidc, 328, 25);

  buttongeac = gtk_button_new ();
  gtk_widget_show (buttongeac);
  gtk_fixed_put (GTK_FIXED (fixed), buttongeac, 904, 392);
  gtk_widget_set_size_request (buttongeac, 120, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttongeac), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>Cancel\n</span></b>"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  comboboxentrygeat = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrygeat);
  gtk_fixed_put (GTK_FIXED (fixed), comboboxentrygeat, 192, 176);
  gtk_widget_set_size_request (comboboxentrygeat, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrygeat), _("Petit_Dej"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrygeat), _("Dejeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrygeat), _("Diner"));

  image22 = create_pixmap (ajyes, "repas-equilibre.jpg");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed), image22, 192, 64);
  gtk_widget_set_size_request (image22, 552, 504);

  labelgeaid = gtk_label_new (_("<b><span\ncolor='red'>ID :\n</span></b> "));
  gtk_widget_show (labelgeaid);
  gtk_fixed_put (GTK_FIXED (fixed), labelgeaid, 128, 112);
  gtk_widget_set_size_request (labelgeaid, 48, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelgeaid), TRUE);

  labelgeat = gtk_label_new (_("<b><span\ncolor='red'>Type :\n</span></b>"));
  gtk_widget_show (labelgeat);
  gtk_fixed_put (GTK_FIXED (fixed), labelgeat, 120, 176);
  gtk_widget_set_size_request (labelgeat, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelgeat), TRUE);

  labelgeanc = gtk_label_new (_("<b><span\ncolor='red'>Nombre de calories :</span></b>"));
  gtk_widget_show (labelgeanc);
  gtk_fixed_put (GTK_FIXED (fixed), labelgeanc, 40, 232);
  gtk_widget_set_size_request (labelgeanc, 152, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelgeanc), TRUE);

  labelgeaqd = gtk_label_new (_("<b><span\ncolor='red'>Quantit\303\251 de d\303\251chets :</span></b>"));
  gtk_widget_show (labelgeaqd);
  gtk_fixed_put (GTK_FIXED (fixed), labelgeaqd, 32, 272);
  gtk_widget_set_size_request (labelgeaqd, 161, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelgeaqd), TRUE);

  labelgead = gtk_label_new (_("<b><span\ncolor='red'>Date :\n</span></b>"));
  gtk_widget_show (labelgead);
  gtk_fixed_put (GTK_FIXED (fixed), labelgead, 88, 336);
  gtk_widget_set_size_request (labelgead, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (labelgead), TRUE);

  labelgeacon = gtk_label_new (_("<b><span\ncolor='red'>Constituants :\n</span></b>"));
  gtk_widget_show (labelgeacon);
  gtk_fixed_put (GTK_FIXED (fixed), labelgeacon, 688, 72);
  gtk_widget_set_size_request (labelgeacon, 144, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelgeacon), TRUE);

  checkbuttongeal = gtk_check_button_new_with_mnemonic (_("Legumes\n"));
  gtk_widget_show (checkbuttongeal);
  gtk_fixed_put (GTK_FIXED (fixed), checkbuttongeal, 832, 88);
  gtk_widget_set_size_request (checkbuttongeal, 152, 48);

  labelgeaeq = gtk_label_new (_("<b><span\ncolor='red'>Equilibr\303\251 :\n</span></b>"));
  gtk_widget_show (labelgeaeq);
  gtk_fixed_put (GTK_FIXED (fixed), labelgeaeq, 736, 232);
  gtk_widget_set_size_request (labelgeaeq, 89, 33);
  gtk_label_set_use_markup (GTK_LABEL (labelgeaeq), TRUE);

  labelgea = gtk_label_new (_("<b><span\ncolor='green'>Ajout\n</span></b>"));
  gtk_widget_show (labelgea);
  gtk_fixed_put (GTK_FIXED (fixed), labelgea, 488, 24);
  gtk_widget_set_size_request (labelgea, 72, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelgea), TRUE);

  g_signal_connect ((gpointer) buttongeaok, "clicked",
                    G_CALLBACK (on_buttongeaok_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongeac, "clicked",
                    G_CALLBACK (on_buttongeac_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajyes, ajyes, "ajyes");
  GLADE_HOOKUP_OBJECT (ajyes, fixed, "fixed");
  GLADE_HOOKUP_OBJECT (ajyes, entrygeaid, "entrygeaid");
  GLADE_HOOKUP_OBJECT (ajyes, spinbuttongeanc, "spinbuttongeanc");
  GLADE_HOOKUP_OBJECT (ajyes, entrygeaqd, "entrygeaqd");
  GLADE_HOOKUP_OBJECT (ajyes, calendargea, "calendargea");
  GLADE_HOOKUP_OBJECT (ajyes, checkbuttongeaf, "checkbuttongeaf");
  GLADE_HOOKUP_OBJECT (ajyes, checkbuttongeac, "checkbuttongeac");
  GLADE_HOOKUP_OBJECT (ajyes, checkbuttongeap, "checkbuttongeap");
  GLADE_HOOKUP_OBJECT (ajyes, radiobuttongeanon, "radiobuttongeanon");
  GLADE_HOOKUP_OBJECT (ajyes, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (ajyes, buttongeaok, "buttongeaok");
  GLADE_HOOKUP_OBJECT (ajyes, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajyes, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajyes, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajyes, label17, "label17");
  GLADE_HOOKUP_OBJECT (ajyes, radiobuttongeaoui, "radiobuttongeaoui");
  GLADE_HOOKUP_OBJECT (ajyes, labelgeasuc, "labelgeasuc");
  GLADE_HOOKUP_OBJECT (ajyes, labelgeaidc, "labelgeaidc");
  GLADE_HOOKUP_OBJECT (ajyes, buttongeac, "buttongeac");
  GLADE_HOOKUP_OBJECT (ajyes, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (ajyes, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ajyes, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajyes, label18, "label18");
  GLADE_HOOKUP_OBJECT (ajyes, comboboxentrygeat, "comboboxentrygeat");
  GLADE_HOOKUP_OBJECT (ajyes, image22, "image22");
  GLADE_HOOKUP_OBJECT (ajyes, labelgeaid, "labelgeaid");
  GLADE_HOOKUP_OBJECT (ajyes, labelgeat, "labelgeat");
  GLADE_HOOKUP_OBJECT (ajyes, labelgeanc, "labelgeanc");
  GLADE_HOOKUP_OBJECT (ajyes, labelgeaqd, "labelgeaqd");
  GLADE_HOOKUP_OBJECT (ajyes, labelgead, "labelgead");
  GLADE_HOOKUP_OBJECT (ajyes, labelgeacon, "labelgeacon");
  GLADE_HOOKUP_OBJECT (ajyes, checkbuttongeal, "checkbuttongeal");
  GLADE_HOOKUP_OBJECT (ajyes, labelgeaeq, "labelgeaeq");
  GLADE_HOOKUP_OBJECT (ajyes, labelgea, "labelgea");

  return ajyes;
}

GtkWidget*
create_myes (void)
{
  GtkWidget *myes;
  GtkWidget *fixed3;
  GtkWidget *entrygemid;
  GtkObject *spinbuttongemnc_adj;
  GtkWidget *spinbuttongemnc;
  GtkWidget *entrygemqd;
  GtkObject *spinbuttongemj_adj;
  GtkWidget *spinbuttongemj;
  GtkObject *spinbuttongemm_adj;
  GtkWidget *spinbuttongemm;
  GtkObject *spinbuttongema_adj;
  GtkWidget *spinbuttongema;
  GtkWidget *checkbuttongemc;
  GtkWidget *checkbuttongemp;
  GtkWidget *checkbuttongemf;
  GtkWidget *checkbuttongeml;
  GtkWidget *radiobuttongemoui;
  GSList *radiobuttongemoui_group = NULL;
  GtkWidget *radiobuttongemnon;
  GtkWidget *vseparator2;
  GtkWidget *buttongemconsulter;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label29;
  GtkWidget *buttongemok;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label27;
  GtkWidget *labelgemer;
  GtkWidget *labelgemsuc;
  GtkWidget *hseparator1;
  GtkWidget *buttongemcancel;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label26;
  GtkWidget *comboboxentrygemt;
  GtkWidget *labelgem;
  GtkWidget *labelgemid;
  GtkWidget *label21;
  GtkWidget *labelgemnc;
  GtkWidget *labelgemqd;
  GtkWidget *labelgemd;
  GtkWidget *label22;
  GtkWidget *labelgemeq;

  myes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (myes), _("Modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (myes), fixed3);

  entrygemid = gtk_entry_new ();
  gtk_widget_show (entrygemid);
  gtk_fixed_put (GTK_FIXED (fixed3), entrygemid, 576, 48);
  gtk_widget_set_size_request (entrygemid, 72, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrygemid), 8226);

  spinbuttongemnc_adj = gtk_adjustment_new (1, 0, 3000, 1, 10, 10);
  spinbuttongemnc = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttongemnc_adj), 1, 0);
  gtk_widget_show (spinbuttongemnc);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttongemnc, 232, 232);
  gtk_widget_set_size_request (spinbuttongemnc, 60, 27);

  entrygemqd = gtk_entry_new ();
  gtk_widget_show (entrygemqd);
  gtk_fixed_put (GTK_FIXED (fixed3), entrygemqd, 232, 272);
  gtk_widget_set_size_request (entrygemqd, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrygemqd), 8226);

  spinbuttongemj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttongemj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttongemj_adj), 1, 0);
  gtk_widget_show (spinbuttongemj);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttongemj, 160, 384);
  gtk_widget_set_size_request (spinbuttongemj, 60, 27);

  spinbuttongemm_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttongemm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttongemm_adj), 1, 0);
  gtk_widget_show (spinbuttongemm);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttongemm, 248, 384);
  gtk_widget_set_size_request (spinbuttongemm, 60, 27);

  spinbuttongema_adj = gtk_adjustment_new (2021, 2006, 2050, 1, 10, 10);
  spinbuttongema = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttongema_adj), 1, 0);
  gtk_widget_show (spinbuttongema);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttongema, 336, 384);
  gtk_widget_set_size_request (spinbuttongema, 60, 27);

  checkbuttongemc = gtk_check_button_new_with_mnemonic (_("Cereales"));
  gtk_widget_show (checkbuttongemc);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbuttongemc, 1008, 144);
  gtk_widget_set_size_request (checkbuttongemc, 118, 24);

  checkbuttongemp = gtk_check_button_new_with_mnemonic (_("Proteines"));
  gtk_widget_show (checkbuttongemp);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbuttongemp, 1008, 168);
  gtk_widget_set_size_request (checkbuttongemp, 120, 48);

  checkbuttongemf = gtk_check_button_new_with_mnemonic (_("fruits"));
  gtk_widget_show (checkbuttongemf);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbuttongemf, 856, 176);
  gtk_widget_set_size_request (checkbuttongemf, 120, 32);

  checkbuttongeml = gtk_check_button_new_with_mnemonic (_("Legumes"));
  gtk_widget_show (checkbuttongeml);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbuttongeml, 856, 144);
  gtk_widget_set_size_request (checkbuttongeml, 112, 32);

  radiobuttongemoui = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (radiobuttongemoui);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttongemoui, 888, 296);
  gtk_widget_set_size_request (radiobuttongemoui, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttongemoui), radiobuttongemoui_group);
  radiobuttongemoui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttongemoui));

  radiobuttongemnon = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (radiobuttongemnon);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobuttongemnon, 888, 344);
  gtk_widget_set_size_request (radiobuttongemnon, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttongemnon), radiobuttongemoui_group);
  radiobuttongemoui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttongemnon));

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed3), vseparator2, 640, 112);
  gtk_widget_set_size_request (vseparator2, 16, 472);

  buttongemconsulter = gtk_button_new ();
  gtk_widget_show (buttongemconsulter);
  gtk_fixed_put (GTK_FIXED (fixed3), buttongemconsulter, 672, 48);
  gtk_widget_set_size_request (buttongemconsulter, 112, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttongemconsulter), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>consulter\n</span></b>"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox11), label29, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  buttongemok = gtk_button_new ();
  gtk_widget_show (buttongemok);
  gtk_fixed_put (GTK_FIXED (fixed3), buttongemok, 840, 456);
  gtk_widget_set_size_request (buttongemok, 80, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttongemok), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>OK\n</span></b>"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox10), label27, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  labelgemer = gtk_label_new ("");
  gtk_widget_show (labelgemer);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemer, 488, 80);
  gtk_widget_set_size_request (labelgemer, 344, 25);

  labelgemsuc = gtk_label_new ("");
  gtk_widget_show (labelgemsuc);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemsuc, 728, 400);
  gtk_widget_set_size_request (labelgemsuc, 352, 25);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed3), hseparator1, 96, 104);
  gtk_widget_set_size_request (hseparator1, 1016, 16);

  buttongemcancel = gtk_button_new ();
  gtk_widget_show (buttongemcancel);
  gtk_fixed_put (GTK_FIXED (fixed3), buttongemcancel, 968, 456);
  gtk_widget_set_size_request (buttongemcancel, 120, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttongemcancel), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>Cancel\n</span></b>"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox9), label26, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  comboboxentrygemt = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrygemt);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentrygemt, 232, 176);
  gtk_widget_set_size_request (comboboxentrygemt, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrygemt), _("Petit_Dej"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrygemt), _("Dejeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrygemt), _("Diner"));

  labelgem = gtk_label_new (_("<b><span\ncolor='green'>Modifier\n</span></b>"));
  gtk_widget_show (labelgem);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgem, 608, 16);
  gtk_widget_set_size_request (labelgem, 72, 17);
  gtk_label_set_use_markup (GTK_LABEL (labelgem), TRUE);

  labelgemid = gtk_label_new (_("<b><span\ncolor='red'>ID :\n</span></b> "));
  gtk_widget_show (labelgemid);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemid, 512, 48);
  gtk_widget_set_size_request (labelgemid, 48, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelgemid), TRUE);

  label21 = gtk_label_new (_("<b><span\ncolor='red'>Type :\n</span></b>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 144, 176);
  gtk_widget_set_size_request (label21, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  labelgemnc = gtk_label_new (_("<b><span\ncolor='red'>Nb_Calories\n</span></b>"));
  gtk_widget_show (labelgemnc);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemnc, 56, 232);
  gtk_widget_set_size_request (labelgemnc, 152, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelgemnc), TRUE);

  labelgemqd = gtk_label_new (_("<b><span\ncolor='red'>Quantit\303\251 de d\303\251chets :\n</span></b>"));
  gtk_widget_show (labelgemqd);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemqd, 56, 272);
  gtk_widget_set_size_request (labelgemqd, 161, 25);
  gtk_label_set_use_markup (GTK_LABEL (labelgemqd), TRUE);

  labelgemd = gtk_label_new (_("<b><span\ncolor='red'>Date :\n</span></b>"));
  gtk_widget_show (labelgemd);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemd, 72, 312);
  gtk_widget_set_size_request (labelgemd, 105, 88);
  gtk_label_set_use_markup (GTK_LABEL (labelgemd), TRUE);

  label22 = gtk_label_new (_("<b><span\ncolor='red'>Constituants :\n</span></b>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 728, 128);
  gtk_widget_set_size_request (label22, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  labelgemeq = gtk_label_new (_("<b><span\ncolor='red'>Equilibr\303\251 :\n</span></b>"));
  gtk_widget_show (labelgemeq);
  gtk_fixed_put (GTK_FIXED (fixed3), labelgemeq, 760, 272);
  gtk_widget_set_size_request (labelgemeq, 89, 33);
  gtk_label_set_use_markup (GTK_LABEL (labelgemeq), TRUE);

  g_signal_connect ((gpointer) buttongemconsulter, "clicked",
                    G_CALLBACK (on_buttongemconsulter_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongemok, "clicked",
                    G_CALLBACK (on_buttongemok_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongemcancel, "clicked",
                    G_CALLBACK (on_buttongemcancel_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (myes, myes, "myes");
  GLADE_HOOKUP_OBJECT (myes, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (myes, entrygemid, "entrygemid");
  GLADE_HOOKUP_OBJECT (myes, spinbuttongemnc, "spinbuttongemnc");
  GLADE_HOOKUP_OBJECT (myes, entrygemqd, "entrygemqd");
  GLADE_HOOKUP_OBJECT (myes, spinbuttongemj, "spinbuttongemj");
  GLADE_HOOKUP_OBJECT (myes, spinbuttongemm, "spinbuttongemm");
  GLADE_HOOKUP_OBJECT (myes, spinbuttongema, "spinbuttongema");
  GLADE_HOOKUP_OBJECT (myes, checkbuttongemc, "checkbuttongemc");
  GLADE_HOOKUP_OBJECT (myes, checkbuttongemp, "checkbuttongemp");
  GLADE_HOOKUP_OBJECT (myes, checkbuttongemf, "checkbuttongemf");
  GLADE_HOOKUP_OBJECT (myes, checkbuttongeml, "checkbuttongeml");
  GLADE_HOOKUP_OBJECT (myes, radiobuttongemoui, "radiobuttongemoui");
  GLADE_HOOKUP_OBJECT (myes, radiobuttongemnon, "radiobuttongemnon");
  GLADE_HOOKUP_OBJECT (myes, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (myes, buttongemconsulter, "buttongemconsulter");
  GLADE_HOOKUP_OBJECT (myes, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (myes, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (myes, image11, "image11");
  GLADE_HOOKUP_OBJECT (myes, label29, "label29");
  GLADE_HOOKUP_OBJECT (myes, buttongemok, "buttongemok");
  GLADE_HOOKUP_OBJECT (myes, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (myes, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (myes, image10, "image10");
  GLADE_HOOKUP_OBJECT (myes, label27, "label27");
  GLADE_HOOKUP_OBJECT (myes, labelgemer, "labelgemer");
  GLADE_HOOKUP_OBJECT (myes, labelgemsuc, "labelgemsuc");
  GLADE_HOOKUP_OBJECT (myes, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (myes, buttongemcancel, "buttongemcancel");
  GLADE_HOOKUP_OBJECT (myes, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (myes, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (myes, image9, "image9");
  GLADE_HOOKUP_OBJECT (myes, label26, "label26");
  GLADE_HOOKUP_OBJECT (myes, comboboxentrygemt, "comboboxentrygemt");
  GLADE_HOOKUP_OBJECT (myes, labelgem, "labelgem");
  GLADE_HOOKUP_OBJECT (myes, labelgemid, "labelgemid");
  GLADE_HOOKUP_OBJECT (myes, label21, "label21");
  GLADE_HOOKUP_OBJECT (myes, labelgemnc, "labelgemnc");
  GLADE_HOOKUP_OBJECT (myes, labelgemqd, "labelgemqd");
  GLADE_HOOKUP_OBJECT (myes, labelgemd, "labelgemd");
  GLADE_HOOKUP_OBJECT (myes, label22, "label22");
  GLADE_HOOKUP_OBJECT (myes, labelgemeq, "labelgemeq");

  return myes;
}

GtkWidget*
create_suppyes (void)
{
  GtkWidget *suppyes;
  GtkWidget *fixed4;
  GtkWidget *entrygesid;
  GtkWidget *labelgeser;
  GtkWidget *labelgessuc;
  GtkWidget *buttongess;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label31;
  GtkWidget *buttongesr;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label32;
  GtkWidget *labelges;
  GtkWidget *labelgesid;

  suppyes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (suppyes), _("supprimer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (suppyes), fixed4);

  entrygesid = gtk_entry_new ();
  gtk_widget_show (entrygesid);
  gtk_fixed_put (GTK_FIXED (fixed4), entrygesid, 96, 40);
  gtk_widget_set_size_request (entrygesid, 128, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrygesid), 8226);

  labelgeser = gtk_label_new ("");
  gtk_widget_show (labelgeser);
  gtk_fixed_put (GTK_FIXED (fixed4), labelgeser, 24, 72);
  gtk_widget_set_size_request (labelgeser, 248, 25);

  labelgessuc = gtk_label_new ("");
  gtk_widget_show (labelgessuc);
  gtk_fixed_put (GTK_FIXED (fixed4), labelgessuc, 24, 112);
  gtk_widget_set_size_request (labelgessuc, 248, 25);

  buttongess = gtk_button_new ();
  gtk_widget_show (buttongess);
  gtk_fixed_put (GTK_FIXED (fixed4), buttongess, 288, 40);
  gtk_widget_set_size_request (buttongess, 112, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttongess), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>Supprimer\n</span></b>"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox12), label31, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  buttongesr = gtk_button_new ();
  gtk_widget_show (buttongesr);
  gtk_fixed_put (GTK_FIXED (fixed4), buttongesr, 288, 88);
  gtk_widget_set_size_request (buttongesr, 112, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttongesr), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>Retour\n</span></b>"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox13), label32, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  labelges = gtk_label_new (_("<b><span\ncolor='green'>Supprimer\n</span></b>"));
  gtk_widget_show (labelges);
  gtk_fixed_put (GTK_FIXED (fixed4), labelges, 160, 8);
  gtk_widget_set_size_request (labelges, 96, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelges), TRUE);

  labelgesid = gtk_label_new (_("<b><span\ncolor='red'>ID :\n</span></b>"));
  gtk_widget_show (labelgesid);
  gtk_fixed_put (GTK_FIXED (fixed4), labelgesid, 32, 40);
  gtk_widget_set_size_request (labelgesid, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelgesid), TRUE);

  g_signal_connect ((gpointer) buttongess, "clicked",
                    G_CALLBACK (on_buttongess_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongesr, "clicked",
                    G_CALLBACK (on_buttongesr_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (suppyes, suppyes, "suppyes");
  GLADE_HOOKUP_OBJECT (suppyes, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (suppyes, entrygesid, "entrygesid");
  GLADE_HOOKUP_OBJECT (suppyes, labelgeser, "labelgeser");
  GLADE_HOOKUP_OBJECT (suppyes, labelgessuc, "labelgessuc");
  GLADE_HOOKUP_OBJECT (suppyes, buttongess, "buttongess");
  GLADE_HOOKUP_OBJECT (suppyes, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (suppyes, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (suppyes, image12, "image12");
  GLADE_HOOKUP_OBJECT (suppyes, label31, "label31");
  GLADE_HOOKUP_OBJECT (suppyes, buttongesr, "buttongesr");
  GLADE_HOOKUP_OBJECT (suppyes, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (suppyes, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (suppyes, image13, "image13");
  GLADE_HOOKUP_OBJECT (suppyes, label32, "label32");
  GLADE_HOOKUP_OBJECT (suppyes, labelges, "labelges");
  GLADE_HOOKUP_OBJECT (suppyes, labelgesid, "labelgesid");

  return suppyes;
}

GtkWidget*
create_cheryes (void)
{
  GtkWidget *cheryes;
  GtkWidget *fixed5;
  GtkWidget *entrygechid;
  GtkWidget *buttongechch;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label34;
  GtkWidget *labelgecher;
  GtkWidget *buttongechr;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label35;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeviewgech;
  GtkWidget *notebook1;
  GtkWidget *fixed6;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeviewgechct;
  GtkWidget *radiobuttongechctpd;
  GSList *radiobuttongechctpd_group = NULL;
  GtkWidget *radiobuttongechctd;
  GtkWidget *radiobuttongechctdn;
  GtkWidget *buttongechct;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label38;
  GtkWidget *labeldechc1;
  GtkWidget *fixed7;
  GtkWidget *scrolledwindow4;
  GtkWidget *treeviewgechce;
  GtkWidget *radiobuttongechcenon;
  GSList *radiobuttongechcenon_group = NULL;
  GtkWidget *buttongechce;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label39;
  GtkWidget *radiobuttongechceoui;
  GtkWidget *labelgechc2;
  GtkWidget *labelgech;
  GtkWidget *labelgechid;

  cheryes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (cheryes), _("chercher"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (cheryes), fixed5);

  entrygechid = gtk_entry_new ();
  gtk_widget_show (entrygechid);
  gtk_fixed_put (GTK_FIXED (fixed5), entrygechid, 112, 56);
  gtk_widget_set_size_request (entrygechid, 88, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrygechid), 8226);

  buttongechch = gtk_button_new ();
  gtk_widget_show (buttongechch);
  gtk_fixed_put (GTK_FIXED (fixed5), buttongechch, 224, 56);
  gtk_widget_set_size_request (buttongechch, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttongechch), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>Chercher\n</span></b>"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox14), label34, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  labelgecher = gtk_label_new ("");
  gtk_widget_show (labelgecher);
  gtk_fixed_put (GTK_FIXED (fixed5), labelgecher, 176, 176);
  gtk_widget_set_size_request (labelgecher, 344, 33);

  buttongechr = gtk_button_new ();
  gtk_widget_show (buttongechr);
  gtk_fixed_put (GTK_FIXED (fixed5), buttongechr, 48, 576);
  gtk_widget_set_size_request (buttongechr, 104, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttongechr), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='red'>Retour\n</span></b>"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox15), label35, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed5), scrolledwindow2, 56, 104);
  gtk_widget_set_size_request (scrolledwindow2, 536, 64);

  treeviewgech = gtk_tree_view_new ();
  gtk_widget_show (treeviewgech);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeviewgech);
  gtk_widget_set_size_request (treeviewgech, 312, 48);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed5), notebook1, 56, 184);
  gtk_widget_set_size_request (notebook1, 536, 360);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow3, 32, 64);
  gtk_widget_set_size_request (scrolledwindow3, 456, 240);

  treeviewgechct = gtk_tree_view_new ();
  gtk_widget_show (treeviewgechct);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeviewgechct);
  gtk_widget_set_size_request (treeviewgechct, 448, 216);

  radiobuttongechctpd = gtk_radio_button_new_with_mnemonic (NULL, _("Petit_Dej"));
  gtk_widget_show (radiobuttongechctpd);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobuttongechctpd, 56, 16);
  gtk_widget_set_size_request (radiobuttongechctpd, 96, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttongechctpd), radiobuttongechctpd_group);
  radiobuttongechctpd_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttongechctpd));

  radiobuttongechctd = gtk_radio_button_new_with_mnemonic (NULL, _("Dejeuner"));
  gtk_widget_show (radiobuttongechctd);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobuttongechctd, 168, 16);
  gtk_widget_set_size_request (radiobuttongechctd, 96, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttongechctd), radiobuttongechctpd_group);
  radiobuttongechctpd_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttongechctd));

  radiobuttongechctdn = gtk_radio_button_new_with_mnemonic (NULL, _("Diner"));
  gtk_widget_show (radiobuttongechctdn);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobuttongechctdn, 280, 16);
  gtk_widget_set_size_request (radiobuttongechctdn, 72, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttongechctdn), radiobuttongechctpd_group);
  radiobuttongechctpd_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttongechctdn));

  buttongechct = gtk_button_new ();
  gtk_widget_show (buttongechct);
  gtk_fixed_put (GTK_FIXED (fixed6), buttongechct, 368, 16);
  gtk_widget_set_size_request (buttongechct, 104, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttongechct), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>Chercher\n</span></b>"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox16), label38, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  labeldechc1 = gtk_label_new (_("Type"));
  gtk_widget_show (labeldechc1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), labeldechc1);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow4, 32, 64);
  gtk_widget_set_size_request (scrolledwindow4, 464, 248);

  treeviewgechce = gtk_tree_view_new ();
  gtk_widget_show (treeviewgechce);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), treeviewgechce);
  gtk_widget_set_size_request (treeviewgechce, 464, 208);

  radiobuttongechcenon = gtk_radio_button_new_with_mnemonic (NULL, _("non"));
  gtk_widget_show (radiobuttongechcenon);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobuttongechcenon, 240, 16);
  gtk_widget_set_size_request (radiobuttongechcenon, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttongechcenon), radiobuttongechcenon_group);
  radiobuttongechcenon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttongechcenon));

  buttongechce = gtk_button_new ();
  gtk_widget_show (buttongechce);
  gtk_fixed_put (GTK_FIXED (fixed7), buttongechce, 376, 16);
  gtk_widget_set_size_request (buttongechce, 104, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttongechce), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>Chercher\n</span></b>"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox17), label39, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  radiobuttongechceoui = gtk_radio_button_new_with_mnemonic (NULL, _("oui"));
  gtk_widget_show (radiobuttongechceoui);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobuttongechceoui, 88, 16);
  gtk_widget_set_size_request (radiobuttongechceoui, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttongechceoui), radiobuttongechcenon_group);
  radiobuttongechcenon_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttongechceoui));

  labelgechc2 = gtk_label_new (_("Equilibree"));
  gtk_widget_show (labelgechc2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), labelgechc2);

  labelgech = gtk_label_new (_("<b><span\ncolor='green'>Chercher\n</span></b>"));
  gtk_widget_show (labelgech);
  gtk_fixed_put (GTK_FIXED (fixed5), labelgech, 200, 16);
  gtk_widget_set_size_request (labelgech, 120, 16);
  gtk_label_set_use_markup (GTK_LABEL (labelgech), TRUE);

  labelgechid = gtk_label_new (_("<b><span\ncolor='red'>ID:\n</span></b>"));
  gtk_widget_show (labelgechid);
  gtk_fixed_put (GTK_FIXED (fixed5), labelgechid, 48, 64);
  gtk_widget_set_size_request (labelgechid, 56, 24);
  gtk_label_set_use_markup (GTK_LABEL (labelgechid), TRUE);

  g_signal_connect ((gpointer) buttongechch, "clicked",
                    G_CALLBACK (on_buttongechch_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongechr, "clicked",
                    G_CALLBACK (on_buttongechr_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongechct, "clicked",
                    G_CALLBACK (on_buttongechct_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongechce, "clicked",
                    G_CALLBACK (on_buttongechce_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (cheryes, cheryes, "cheryes");
  GLADE_HOOKUP_OBJECT (cheryes, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (cheryes, entrygechid, "entrygechid");
  GLADE_HOOKUP_OBJECT (cheryes, buttongechch, "buttongechch");
  GLADE_HOOKUP_OBJECT (cheryes, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (cheryes, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (cheryes, image14, "image14");
  GLADE_HOOKUP_OBJECT (cheryes, label34, "label34");
  GLADE_HOOKUP_OBJECT (cheryes, labelgecher, "labelgecher");
  GLADE_HOOKUP_OBJECT (cheryes, buttongechr, "buttongechr");
  GLADE_HOOKUP_OBJECT (cheryes, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (cheryes, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (cheryes, image15, "image15");
  GLADE_HOOKUP_OBJECT (cheryes, label35, "label35");
  GLADE_HOOKUP_OBJECT (cheryes, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (cheryes, treeviewgech, "treeviewgech");
  GLADE_HOOKUP_OBJECT (cheryes, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (cheryes, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (cheryes, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (cheryes, treeviewgechct, "treeviewgechct");
  GLADE_HOOKUP_OBJECT (cheryes, radiobuttongechctpd, "radiobuttongechctpd");
  GLADE_HOOKUP_OBJECT (cheryes, radiobuttongechctd, "radiobuttongechctd");
  GLADE_HOOKUP_OBJECT (cheryes, radiobuttongechctdn, "radiobuttongechctdn");
  GLADE_HOOKUP_OBJECT (cheryes, buttongechct, "buttongechct");
  GLADE_HOOKUP_OBJECT (cheryes, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (cheryes, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (cheryes, image16, "image16");
  GLADE_HOOKUP_OBJECT (cheryes, label38, "label38");
  GLADE_HOOKUP_OBJECT (cheryes, labeldechc1, "labeldechc1");
  GLADE_HOOKUP_OBJECT (cheryes, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (cheryes, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (cheryes, treeviewgechce, "treeviewgechce");
  GLADE_HOOKUP_OBJECT (cheryes, radiobuttongechcenon, "radiobuttongechcenon");
  GLADE_HOOKUP_OBJECT (cheryes, buttongechce, "buttongechce");
  GLADE_HOOKUP_OBJECT (cheryes, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (cheryes, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (cheryes, image17, "image17");
  GLADE_HOOKUP_OBJECT (cheryes, label39, "label39");
  GLADE_HOOKUP_OBJECT (cheryes, radiobuttongechceoui, "radiobuttongechceoui");
  GLADE_HOOKUP_OBJECT (cheryes, labelgechc2, "labelgechc2");
  GLADE_HOOKUP_OBJECT (cheryes, labelgech, "labelgech");
  GLADE_HOOKUP_OBJECT (cheryes, labelgechid, "labelgechid");

  return cheryes;
}

GtkWidget*
create_bestyes (void)
{
  GtkWidget *bestyes;
  GtkWidget *fixed8;
  GtkObject *spinbuttonbestmenu_adj;
  GtkWidget *spinbuttonbestmenu;
  GtkWidget *labelgebest;
  GtkWidget *buttongebestr;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label41;
  GtkWidget *buttonbestmenu;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label43;

  bestyes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (bestyes), _("Meilleur Menu"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (bestyes), fixed8);

  spinbuttonbestmenu_adj = gtk_adjustment_new (1, 1, 4, 1, 10, 10);
  spinbuttonbestmenu = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonbestmenu_adj), 1, 0);
  gtk_widget_show (spinbuttonbestmenu);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbuttonbestmenu, 208, 8);
  gtk_widget_set_size_request (spinbuttonbestmenu, 60, 27);

  labelgebest = gtk_label_new ("");
  gtk_widget_show (labelgebest);
  gtk_fixed_put (GTK_FIXED (fixed8), labelgebest, 32, 48);
  gtk_widget_set_size_request (labelgebest, 432, 33);

  buttongebestr = gtk_button_new ();
  gtk_widget_show (buttongebestr);
  gtk_fixed_put (GTK_FIXED (fixed8), buttongebestr, 192, 96);
  gtk_widget_set_size_request (buttongebestr, 104, 37);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttongebestr), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='red'>Retour\n</span></b>"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox18), label41, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  buttonbestmenu = gtk_button_new ();
  gtk_widget_show (buttonbestmenu);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonbestmenu, 312, 8);
  gtk_widget_set_size_request (buttonbestmenu, 66, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonbestmenu), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("<b><span\ncolor='green'>OK\n</span></b>"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox20), label43, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  g_signal_connect ((gpointer) buttongebestr, "clicked",
                    G_CALLBACK (on_buttongebestr_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonbestmenu, "clicked",
                    G_CALLBACK (on_buttonbestmenu_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bestyes, bestyes, "bestyes");
  GLADE_HOOKUP_OBJECT (bestyes, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (bestyes, spinbuttonbestmenu, "spinbuttonbestmenu");
  GLADE_HOOKUP_OBJECT (bestyes, labelgebest, "labelgebest");
  GLADE_HOOKUP_OBJECT (bestyes, buttongebestr, "buttongebestr");
  GLADE_HOOKUP_OBJECT (bestyes, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (bestyes, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (bestyes, image18, "image18");
  GLADE_HOOKUP_OBJECT (bestyes, label41, "label41");
  GLADE_HOOKUP_OBJECT (bestyes, buttonbestmenu, "buttonbestmenu");
  GLADE_HOOKUP_OBJECT (bestyes, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (bestyes, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (bestyes, image20, "image20");
  GLADE_HOOKUP_OBJECT (bestyes, label43, "label43");

  return bestyes;
}

