/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestionyes (void);
GtkWidget* create_ajyes (void);
GtkWidget* create_myes (void);
GtkWidget* create_suppyes (void);
GtkWidget* create_cheryes (void);
GtkWidget* create_bestyes (void);
