/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *gestionyes;
 /* GtkWidget *ajyes;
  GtkWidget *myes;
  GtkWidget *suppyes;
  GtkWidget *cheryes;
  GtkWidget *bestyes;*/

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  //add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");
add_pixmap_directory ("../pixmaps");
  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  gestionyes = create_gestionyes ();
  gtk_widget_show (gestionyes);
  /*ajyes = create_ajyes ();
  gtk_widget_show (ajyes);
  myes = create_myes ();
  gtk_widget_show (myes);
  suppyes = create_suppyes ();
  gtk_widget_show (suppyes);
  cheryes = create_cheryes ();
  gtk_widget_show (cheryes);
  bestyes = create_bestyes ();
  gtk_widget_show (bestyes);*/

  gtk_main ();
  return 0;
}

